- name: install flatpak Slack
  tags: 
    - packages
    - flatpak
  become: yes
  flatpak:
    name:  com.slack.Slack
    state: present

- name: install flatpak Sublime
  tags: 
    - packages
    - flatpak
  become: yes
  flatpak:
    name:  com.sublimetext.three
    state: present

- name: install flatpak Spotify
  tags: 
    - packages
    - flatpak
  become: yes
  flatpak:
    name:  com.spotify.Client
    state: present

- name: install flatpak Peek
  tags: 
    - packages
    - flatpak
  become: yes
  flatpak:
    name:  com.uploadedlobster.peek
    state: present
