- name: Create .zsh.d
  file: 
    path: $HOME/.zsh.d/
    state: directory

- name: Install Antigen
  get_url: 
    url: https://git.io/antigen
    dest: $HOME/.zsh.d/antigen.zsh

- name: Activate ZSH
  become: true
  user:
    name: mat
    shell: /bin/zsh

- name: Copy dotfiles for zsh
  copy:
    src: "{{item}}"
    dest: $HOME
  with_items:
    - .bash_profile
    - .zshrc
    - .zsh.d
