- name: "install micro"
  tags: snaps
  become: yes
  snap:
    name: micro
    classic: yes

- name: "install keepassxc"
  tags: snaps
  become: yes
  snap:
    name: keepassxc

- name: "install sublime"
  tags: snaps
  become: yes
  snap:
    name:  sublime-text
    classic: yes

- name: "install slack"
  tags: snaps
  become: yes
  snap:
    name: slack
    classic: yes

- name: "install spotify"
  tags: snaps
  become: yes
  snap:
    name: spotify
