---
- name: Install it all
  hosts: default
  roles:
     - name: shell
     - name: packages
     - name: docker
     - name: gnome
     # - name: polybar

- name: Install gnome extensions
  hosts: default
  vars:
    gnome_extension_ids:
      - "8"    # Places Status Indicator
      - "15"   # AlternateTab
      - "16"   # Auto Move Windows
      - "19"   # User Themes
      - "545"  # Hide Top Bar
      - "1128" # Remove Alt+Tab Delay
      - "1267" # No Title Bar
      - "1403" # Hide Activities Button
  tags: "gnome, gnome-extensions"
  roles:
      - jaredhocutt.gnome_extensions
  environment:
    ANSIBLE_ROLES_PATH: ~/.ansible/roles
